apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-portfolio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SALMAFALLAHI/devops-portfolio.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true